### ISSUE TITLE
Passes through `-O0` because of unset default `debug=T`

### ISSUE THREAD

**Issue by JZL** [r-lib/pkgload#224]
Hi,

I've been chasing this performance hit when using `load_all` to quickly test out a RCPP package. Finally tracing it down, if I do
`devtools::load_all("PKG_NAME")` it goes

- `devtools::load_all("PKG_NAME")`
- `pkgbuild::compile_dll(path, quiet = quiet)`  - [here](https://github.com/r-lib/pkgload/blob/eb91786bd581552c81bd6945aa23bb30bab00203/R/load.R#L175)
- `compile_dll` which has `debug=T` as the unchanged default [here](https://github.com/r-lib/pkgbuild/blob/11cb9e901582246ff62769d6339e6d1d01a4e4c6/R/compile-dll.R#L24)
- which is passed to `compiler_flags(debug)`
- which sets `-O0` in the compile vars so nothing is inlined or optimized

So it uses a lot of the packages within `r-lib`. Currently there's no way of overriding this because compile_dll doesn't allow passing a changed `debug` onwards. Arguably this could be changed in `pkgbuild`'s default because if anyone is going to the trouble of using RCPP, they probably want all optimizations. Personally, I'm just loading a fork of pkgbuild which always sets Debug=F. But `-O0` is so debugger friendly, it leads to very strange performance penalties.

EDIT: Wow, yeah `-O3` is so much faster than `-O0` and I needed to play so many fewer tricks to make it happen

**Comment by lionel-** [comment]
Development builds are not optimised by default so that you get full backtraces and full browsing in debuggers. You can set `-O3` in your personal Makevars file.

**Comment by JZL** [comment]
Ok great, thanks

**Comment by bnprks** [comment]
I have found that setting `-O3` or `-O2` in my `~/.R/Makevars` file is insufficient because the `compiler_flags` settings overwrite the `CFLAGS` and `CXXFLAGS`  causing `-O0` to still get used.

For others in the same situation, here is an ugly workaround that overrides the `pkgbuild::compiler_flags` function in the `pkgbuild` namespace to allow manually setting the desired flags. Only for use during personal development, of course, but it's helpful when debugging code that runs very slowly with `-O0`
```R
# Overwrite devtools::load_all() default to use -O2 optimization level rather than -O0
compiler_flags <- function(debug=FALSE) {
    c(
        CFLAGS = "-UNDEBUG -Wall -pedantic -g -O2",
        CXXFLAGS = "-UNDEBUG -Wall -pedantic -g -O2",
        CXX11FLAGS = "-UNDEBUG -Wall -pedantic -g -O2",
        CXX14FLAGS = "-UNDEBUG -Wall -pedantic -g -O2",
        CXX17FLAGS = "-UNDEBUG -Wall -pedantic -g -O2",
        CXX20FLAGS = "-UNDEBUG -Wall -pedantic -g -O2",
        FFLAGS = "-g -O2",
        FCFLAGS = "-g -O2"
    )
}
assignInNamespace("compiler_flags", compiler_flags, "pkgbuild")
```

**Comment by assaron** [comment]
@lionel- Would adding `debug` parameter for `load_all()` to be passed through conflict with something? It should be an easy fix, I can make a PR. I'm interested in checking the Rcpp code performance, and constantly forget about this problem and how it can be fixed. 

I'm also not sure that compiling with debug flags by default is the best option. The function description literally says that "load_all() loads a package. It roughly simulates what happens when a package is installed and loaded with library(), without having to first install the package.", which is currently gives a wrong impression that the behavior of `load_all()` tries to simulate install and `library()` as close as possible. So I would argue that `debug=FALSE` should be the default option.

**Comment by assaron** [comment]
> You can set -O3 in your personal Makevars file.

Also, this does not seem to work now (as confirmed by @bnprks above). I think it worked previously, consistent with the `debug` flag description: "If TRUE, and if no user Makevars is found, then the build runs without optimisation (-O0) and with debug symbols (-g)." But I have Makevars file and I get debug compile flags anyway. Is this a bug?

**Comment by JZL** [comment]
It's been a long time so I'm happy just remembering to use my fork and be wary if RCpp seems slower than expected.

But I do think it's an asymmetrically difficult default to have for newcomers because if you're trying to debug, but there are no debug symbols/stack traces, it's clear that you have to make sure it's `-O0` and obvious when you have succeeded in adding them. The debuggers could even detect such a thing and give a helpful error message

But if your code is (way) slower than it 'could' be without `-O3` , there's no obvious indication something is 'wrong' (or at least easily-fixable-suboptimal) and it's not obvious to a user if their attempted fix succeeded unless they carefully check the compilation logs

**Comment by lionel-** [comment]
Load-all is for simulating installation of a package for _development_ purposes and passing debug flags is crucial to the dev workflow.

I think measuring performance needs to be done on an installed version of the package, with bytecode compiled R, optimisation flags, etc.
