### ISSUE TITLE
Should `helper.R` assume the testthat namespace is attached?

### ISSUE THREAD

**Issue by jennybc** [r-lib/pkgload#56]
I have a `helper.R` file that defines custom skippers and, depending on the situation, might call one of them in `helper.R`, in order to emit a message for the benefit of travis and appveyor logs.

This taught me that `skip()` can't be found when `helper.R` is run via `check()` (whereas it is found when the helpers are run via `test()`).

Should we write `helper.R` to assume that the testthat namespace is attached or not?

https://github.com/r-lib/pkgload/blob/80a649330317a3e8426a94acd33c82011c31b90d/R/load.r#L193-L198

**Comment by jimhester** [comment]
testthat _is_ attached when running R CMD check, see the example package [testHelper](https://github.com/jimhester/testHelper), which simply defines a helper

**Comment by jennybc** [comment]
I'm not really asking about `load_all()` as much as I'm asking about `check()` (vs. `test()`).

I pulled the testHelper package and ran `devtools::check()` in the Console. I also gave the package an inert `.Rprofile` so my usual `.Rprofile` doesn't get read, which loads testthat, and has been confusing matters.

I get failure with 'foo' with `devtools::check()`.
Then I get failure with 'bar' with `devtools::test()`.
Then I get failure with ... 'bar' with `devtools::check()`. So, it changes. 🤔

<img width="492" alt="screen shot 2017-08-29 at 9 36 13 pm" src="https://user-images.githubusercontent.com/599454/29855658-40d206b4-8d02-11e7-9dd1-362ba2f20899.png">

I consistently get failure with 'foo' with the IDE workflow = *Build > Check*.

I made a PR there to make the message even more transparent, so here's the screenshot with that:

<img width="739" alt="screen shot 2017-08-29 at 9 39 45 pm" src="https://user-images.githubusercontent.com/599454/29855703-a082c800-8d02-11e7-8b64-79a4ba853d0d.png">

<img width="494" alt="screen shot 2017-08-29 at 9 45 18 pm" src="https://user-images.githubusercontent.com/599454/29855786-64efe02e-8d03-11e7-8d92-b0d67d006b42.png">

**Comment by jimhester** [comment]
Ah, this is actually and issue with `load_all()` that #57 will fix.

This is happening because `devtools::check()` has a default argument `document = TRUE`, so it calls `document()` before checking the package, and `document()` uses `load_all()` to load the package before documenting.

`devtools::check(document = FALSE)` fails with `bar` as expected.

I feel like we should change the default to `document = FALSE`, this is not the first time I have run into issues like this...

**Comment by jennybc** [comment]
Is there any chance `testthat::source_test_helpers()` should also source `tests/testthat.R`? I think I'm really looking for an official policy whether `helpers.R` should be written as if `tests/testthat.R` has been sourced previously or not.

I'm pretty agnostic on the general `load_all()` and `document()` issues, as I've not thought about them deeply and defer to you.

**Comment by jimhester** [comment]
`source_test_helpers()` can't really source `tests/testthat.R` as it typically contains a call to `test_check()` (which shouldn't be run) and sometimes contains code that should only be run when running `R CMD check` rather than `devtools::test()`.

`helper.R` _has_ to be written as if `tests/testthat.R` was sourced (as this is what happens during `R CMD check`), but it also cannot rely on it being sourced (for interactive use). Generally the code in `tests/testthat.R` should be code you expect to run only when running `R CMD check` outside of devtools.

**Comment by jennybc** [comment]
OK, very helpful. Needless to say, I have long since namespaced these calls to `skip()`, but just wanted to get to the bottom of it.
