### ISSUE TITLE
unable to run dev_example 

### ISSUE THREAD

**Issue by cderv** [r-lib/pkgload#85]
I do not manage to use `dev_example` and I think something is off. 

https://github.com/r-lib/pkgload/blob/0ef4f58cd8135e9e77c21243e466b9739e608bde/R/dev-example.r#L20-L25

I used htmltools 📦 for illustration.

First, I get an error if package is not load with `load_all` before calling
```r
> pkgload::dev_example("builder")
Error: Could not find development topic 'builder'
```
this error if from `dev_help` that needs a package to be loaded. 
This behavior seems ok. but `dev_example` also call `load_all` internally and that is causing an issue
```r
> pkgload::load_all()
Loading htmltools
> pkgload::dev_example("builder")
Error in normalizePath(path.expand(path), winslash, mustWork) : 
  path[1]="htmltools": Le fichier spécifié est introuvable
```
I think this is because `load_all` is called using the package name and not the path of the dev package (often `"."` I think as `load_all` default).
 
This second line in `dev_example` is causing the issue, and I think it is not needed as first call to `dev_help` require already a `load_all` call. 

Am I missing something or is there a bug here ?

**Comment by jimhester** [comment]
I am pretty sure this is a bug and the function is broken.

**Comment by riccardoporreca** [comment]
I confirm @cderv 's perception of `dev_example()` being broken by the internal call to `load_all(topic$pkg, quiet = quiet)`, since `topic$pkg` is the package name and not the path to the development version of the package. This only works when we are in the parent directory of the package, which is not the typical setup of RStudio projects for packages.

Without the `load_all()` call everything works fine (tested in my [forked version](https://github.com/riccardoporreca/pkgload)). Note that not calling `load_all()` is in line with `dev_help()`, where the development version of the package is assumed to be pre-loaded via `load_all()`, and that the initial  `topic <- dev_help(topic)` would detect if it is not the case.

I find **devtools** and its spin-off packages like **pkgload** great tools for development, and use `dev_example()` / `dev_help()` on a daily basis. I currently switched to my fork [riccardoporreca/pkgload](https://github.com/riccardoporreca/pkgload) to continue having a fully-functional version of `dev_example()`.
