### ISSUE TITLE
Minimal unit test breaks package

### ISSUE THREAD

**Issue by ekernf01** [r-lib/pkgload#88]
Hi devtools devs,

I am encountering an issue that I think is a version of https://github.com/r-lib/devtools/issues/192 . A full explanation is here on SO.

https://stackoverflow.com/questions/53572652/r-testthat-and-devtools-why-does-a-minimal-unit-test-break-my-package

Basically, I my package works until I run even an empty unit test with `devtools::test()`. Then it stops working because it can no longer find S4 methods from the `Matrix` package. It seems to be something about the mop-up, because the tests run fine once and then never again until restarting R. 

Do you think this is a `devtools` issue? Could you suggest a workaround so I can continue using unit tests while I work on this package?

Thanks!

**Comment by lionel-** [comment]
You need to import all the generics you're using in your package namespace:

```r
#' @importFrom Matrix t tcrossprod colSums rowMeans
NULL
```

This will fix the issue that you're observing and you'll be able the tests multiple times in the same session.

Also this will allow other packages that import `Matrix::t` to consistently use your custom methods. Currently, since you're calling `setMethod()` in your package, you're creating a new `t()` generic local to your namespace whenever Matrix is not attached to the search path at load-time (this is why it worked the first time you ran the tests). This prevents other packages using `Matrix::t()` to access your methods. Importing `Matrix::t()` explicitly will fix this because you'll never create a local generic for `t()`.
